[feature] add fulllread
DJ51012/EyesAndEars_SSD_Project pull request #24
Opened 2024-07-09 07:02 UTC by kimmjinhong

fullwtite sequence :
1. ssd.read()
2. fileio.open()
3. fileio.read()
4. repeat 1~3

full read를 적용합니다.
리뷰부탁드립니다.

2024-07-09 07:19 UTC, RoyHeeseungYoo requested changes

2024-07-09 07:19 UTC, RoyHeeseungYoo commented on TestShell/testcmd.h
> +			FILE* fd = fio->Open(FILE_NAME_NAND, "r");
read 직후 nand.txt 를 읽으면 index 값과 무관하게 실제로 write 된 lba 에 대해서만 출력 될 것 같습니다.
read 와 연결되어 있는 result.txt 를 읽는 방법이 필요해 보입니다.

2024-07-09 07:48 UTC, RoyHeeseungYoo commented on TestShell/testcmd.h
> +				std::cout << buf;
Open 된 fd 를 Close 해서 자원 누수를 방지해주면 좋을 것 같습니다.

2024-07-09 23:14 UTC, kimmjinhong commented on TestShell/testcmd.h
> +			FILE* fd = fio->Open(FILE_NAME_NAND, "r");
ssddriver mock에서 nand.txt(std::string fileNandContent)로 부터 원하는 index를 읽어 올수 있도록 변경 하였습니다.
그래서 nand.txt(std::string fileNandContent)가 아닌 result.txt(std::string result)에서 값을 읽어 오도록 수정 하였습니다.
TestShellFixture 및 read부분에 중복되는 코드는 refactoring에서 정리 하도록 하겠습니다.

2024-07-10 00:17 UTC, kimmjinhong commented on TestShell/testcmd.h
> +				std::cout << buf;
fd를 close하도록 추가하였습니다.

2024-07-10 00:19 UTC, RoyHeeseungYoo approved these changes
fullread 기능 구현 및 관련 개선 사항 확인 하였습니다.
머지 부탁드립니다.

2024-07-10 00:19 UTC, merged